apiVersion: extensions/v1beta1
kind: "DaemonSet"
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v0.12.24
          ports:
            - containerPort: 24224
